language: php
php:
- 5.3
env:
- DB=mysql
before_script:
- composer install
- pyrus install http://phptal.org/latest.tar.gz
- pear install pear/PHP_CodeSniffer
- phpenv rehash
script: phpcs --standard=PSR2 --ignore=vendor/*,*/expdf/*,*/jpgraph/*  /home/travis/build/sbarrat/cni